<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Faker\Factory as Faker;
use Illuminate\Support\Facades\DB;
use App\Models\Laptop;

class LaptopDataSeeder extends Seeder
{
    // Insert laptops
    public function run(): void
    {
        $faker = Faker::create();
        $quantity = $faker->numberBetween(0, 100);
        DB::table('laptops')->insert([
            ['name' => 'Laptop gaming MSI Thin 15 B13UC 2044VN',
             'category_id' => 1,
             'manufactory_id' => 8,
             'CPU' => 'Intel Core i7-13620H (3.6GHz~4.9GHz) 10 Nhân 16 Luồng',
             'VGA' => 'NVIDIA® GeForce RTX™ 3050 Laptop GPU, Up to 1172.5MHz Boost Clock 45W Maximum Graphics Power with Dynamic Boost.',
             'RAM' => '16GB (2 x 8GB) DDR4 3200MHz (2x SO-DIMM socket, up to 64GB SDRAM)',
             'hard_drive' => 'SSD NVMe PCIe 512GB Gen4x4 (1 khe)',
             'display' => '15.6" FHD (1920x1080), 144Hz, IPS-Level, 45% NTSC, 65% sRGB',
             'battery' => '3-Cell 52.4 Battery (Whr)',
             'weight' => '1.86',
             'material' => 'Nhựa',
             'OS' => 'Windows 11 Home',
             'size' => '359 x 254 x 21.7 mm',
             'ports' => '1x Type-C (USB3.2 Gen1 / DP)
                        3x Type-A USB3.2 Gen1
                        1x HDMI™ (4K @ 30Hz)
                        1x RJ45',
             'keyboard' => 'Single Backlit Keyboard (Blue)',
             'audio' => '2x 2W Speaker',
             'network_and_connection' => '802.11 ax Wi-Fi 6E, LAN Gigabit Ethernet, Bluetooth v5.3',
             'security' => 'Windows Defence',
             'quantity' => $quantity,
             'price' => '20990000',
             'status' => 'Còn hàng',
             'created_at' => now()], 
        ]);

        $quantity = $faker->numberBetween(0, 100);
        DB::table('laptops')->insert([     
            ['name' => 'LAPTOP ACER ASPIRE 7 A715-76-53PJ',
             'category_id' => 2,
             'manufactory_id' => 3,
             'CPU' => 'Intel® Core™ i5-12450H (3.3GHz upto 4.4Ghz/12MB cache)',
             'VGA' => 'Intel® UHD Graphics',
             'RAM' => '16GB DDR4 3200Mhz (8GB * 2)',
             'hard_drive' => '512GB SSD PCIe NVMe (nâng cấp tối đa 1 TB SSD PCIe Gen4, 16 Gb/s, NVMe)',
             'display' => '15.6 inch FHD IPS (1920 x 1080) Slim Benzel; ComfyView IPS LED',
             'battery' => '50Wh Li-ion battery',
             'weight' => '2.1',
             'material' => 'Nhôm (Mặt A),Nhựa',
             'OS' => 'Win 11 Home',
             'size' => '362.3 (W) x 237.4 (D) x 19.9 (H) mm',
             'ports' => '1x USB Type-C™ port, 1x USB 3.2 Gen 1 featuring power off USB charging, 2x USB 3.2 Gen 1, 1x HDMI® 2.0 port with HDCP support, 1x DC-in jack for AC adapter, 1x Ethernet (RJ-45) port, 1x 3.5 mm headphone/speaker jack',
             'keyboard' => 'LED RGB',
             'audio' => 'Acer TrueHarmony technology',
             'network_and_connection' => 'Intel® Wireless Wi-Fi 6E AX211 (2x2), LAN 10/100/1000/Gigabits Base T, Bluetooth v5.1',
             'security' => 'Mở khóa vân tay',
             'quantity' => $quantity,
             'price' => '20990000',
             'status' => 'Còn hàng',
             'created_at' => now()],
        ]);

        $quantity = $faker->numberBetween(0, 100);
        DB::table('laptops')->insert([ 
            ['name' => 'Laptop ASUS Vivobook 15 OLED A1505VA MA469W',
             'category_id' => 2,
             'manufactory_id' => 1,
             'CPU' => '	Intel® Core™ i9-13900H Processor 2.6 GHz (24MB Cache, up to 5.4 GHz, 14 cores, 20 Threads)',
             'VGA' => 'Intel Iris Xe Graphics (with dual channel memory)',
             'RAM' => '	16GB (8GB Onboard + 8GB Sodimm) DDR4 3200MHz',
             'hard_drive' => '512GB M.2 NVMe™ PCIe® 3.0 SSD (1 slot, support M.2 2280 PCIe 3.0x4)',
             'display' => '2.8K (2880 x 1620) OLED 16:9, 120Hz 0.2ms, 600nits, 100% DCI-P3, Glossy display, Screen-to-body ratio: 86%, PANTONE Validated, VESA CERTIFIED Display HDR True Black 600',
             'battery' => '50WHrs, 3S1P, 3-cell Li-ion',
             'weight' => '1.7',
             'material' => 'Plastic (Top, Bottom, LCD cover)',
             'OS' => 'Windows 11 Home',
             'size' => '35.68 x 22.76 x 1.99 cm',
             'ports' => '1x USB 2.0 Type-A
                        1x USB 3.2 Gen 1 Type-C support power delivery
                        2x USB 3.2 Gen 1 Type-A
                        1x HDMI 1.4
                        1x 3.5mm Combo Audio Jack
                        1x DC-in',
             'keyboard' => 'Chiclet Keyboard with Num-key',
             'audio' => 'SonicMaster',
             'network_and_connection' => 'Wi-Fi 6E(802.11ax) (Dual band) 1*1, Bluetooth® 5.3 Wireless Card',
             'security' => 'Vân tay',
             'quantity' => $quantity,
             'price' => '20990000',
             'status' => 'Còn hàng',
             'created_at' => now()],
        ]);

        $quantity = $faker->numberBetween(0, 100);
        DB::table('laptops')->insert([ 
             ['name' => 'Laptop ASUS Zenbook 14 OLED UX3405MA PP152W',
             'category_id' => 2,
             'manufactory_id' => 1,
             'CPU' => 'Intel® Core™ Ultra 7 Processor 155H 1.4 GHz (24MB Cache, up to 4.8 GHz, 16 cores, 22 Threads); Intel® AI Boost NPU',
             'VGA' => 'Intel® Arc™ Graphics',
             'RAM' => '32GB LPDDR5X on board Dual-channel (Không nâng cấp)',
             'hard_drive' => '1TB M.2 NVMe™ PCIe® 4.0 SSD',
             'display' => '14.0-inch 3K (2880 x 1800) OLED 16:10, LED Backlit, 0.2ms, 120Hz, 400nits, 600nits HDR peak brightness, 100% DCI-P3, Glossy display, Tỷ lệ màn hình trên thân máy 87%',
             'battery' => '75WHrs, 2S2P, 4-cell Li-ion',
             'weight' => '1.2',
             'material' => 'Nhôm',
             'OS' => 'Windows 11 Home',
             'size' => '31.24 x 22.01 x 1.49 ~ 1.49 cm',
             'ports' => '1x USB 3.2 Gen 1 Type-A
                        2x Thunderbolt™ 4 supports display / power delivery
                        1x HDMI 2.1 TMDS
                        1x 3.5mm Combo Audio Jack',
             'keyboard' => 'Support NumberPad, Backlit Chiclet Keyboard',
             'audio' => 'Harman/Kardon (Premium)',
             'network_and_connection' => 'Wi-Fi 6E(802.11ax) (Dual band) 2*2 + Bluetooth® 5.3',
             'security' => 'IR webcam with Windows Hello support, Trusted Platform Module (TPM) 2.0',
             'quantity' => $quantity,
             'price' => '20990000',
             'status' => 'Còn hàng',
             'created_at' => now()],
        ]);
            //  ['name' => 'Laptop gaming MSI Thin 15 B13UC 2044VN',
            //  'category_id' => 1,
            //  'manufactory_id' => 8,
            //  'CPU' => '',
            //  'VGA' => '',
            //  'RAM' => '',
            //  'hard_drive' => '',
            //  'display' => '',
            //  'battery' => '',
            //  'weight' => '',
            //  'material' => '',
            //  'OS' => '',
            //  'size' => '',
            //  'ports' => '',
            //  'keyboard' => '',
            //  'audio' => '',
            //  'network_and_connection' => '',
            //  'security' => '',
            //  'quantity' => $quantity,
            //  'price' => '20990000',
            //  'status' => 'Còn hàng',
            //  'created_at' => now()],

            //  ['name' => 'Laptop gaming MSI Thin 15 B13UC 2044VN',
            //  'category_id' => 1,
            //  'manufactory_id' => 8,
            //  'CPU' => '',
            //  'VGA' => '',
            //  'RAM' => '',
            //  'hard_drive' => '',
            //  'display' => '',
            //  'battery' => '',
            //  'weight' => '',
            //  'material' => '',
            //  'OS' => '',
            //  'size' => '',
            //  'ports' => '',
            //  'keyboard' => '',
            //  'audio' => '',
            //  'network_and_connection' => '',
            //  'security' => '',
            //  'quantity' => $quantity,
            //  'price' => '20990000',
            //  'status' => 'Còn hàng',
            //  'created_at' => now()],

            //  ['name' => 'Laptop gaming MSI Thin 15 B13UC 2044VN',
            //  'category_id' => 1,
            //  'manufactory_id' => 8,
            //  'CPU' => '',
            //  'VGA' => '',
            //  'RAM' => '',
            //  'hard_drive' => '',
            //  'display' => '',
            //  'battery' => '',
            //  'weight' => '',
            //  'material' => '',
            //  'OS' => '',
            //  'size' => '',
            //  'ports' => '',
            //  'keyboard' => '',
            //  'audio' => '',
            //  'network_and_connection' => '',
            //  'security' => '',
            //  'quantity' => $quantity,
            //  'price' => '20990000',
            //  'status' => 'Còn hàng',
            //  'created_at' => now()],

            //  ['name' => 'Laptop gaming MSI Thin 15 B13UC 2044VN',
            //  'category_id' => 1,
            //  'manufactory_id' => 8,
            //  'CPU' => '',
            //  'VGA' => '',
            //  'RAM' => '',
            //  'hard_drive' => '',
            //  'display' => '',
            //  'battery' => '',
            //  'weight' => '',
            //  'material' => '',
            //  'OS' => '',
            //  'size' => '',
            //  'ports' => '',
            //  'keyboard' => '',
            //  'audio' => '',
            //  'network_and_connection' => '',
            //  'security' => '',
            //  'quantity' => $quantity,
            //  'price' => '20990000',
            //  'status' => 'Còn hàng',
            //  'created_at' => now()],

            //  ['name' => 'Laptop gaming MSI Thin 15 B13UC 2044VN',
            //  'category_id' => 1,
            //  'manufactory_id' => 8,
            //  'CPU' => '',
            //  'VGA' => '',
            //  'RAM' => '',
            //  'hard_drive' => '',
            //  'display' => '',
            //  'battery' => '',
            //  'weight' => '',
            //  'material' => '',
            //  'OS' => '',
            //  'size' => '',
            //  'ports' => '',
            //  'keyboard' => '',
            //  'audio' => '',
            //  'network_and_connection' => '',
            //  'security' => '',
            //  'quantity' => $quantity,
            //  'price' => '20990000',
            //  'status' => 'Còn hàng',
            //  'created_at' => now()],

            //  ['name' => 'Laptop gaming MSI Thin 15 B13UC 2044VN',
            //  'category_id' => 1,
            //  'manufactory_id' => 8,
            //  'CPU' => '',
            //  'VGA' => '',
            //  'RAM' => '',
            //  'hard_drive' => '',
            //  'display' => '',
            //  'battery' => '',
            //  'weight' => '',
            //  'material' => '',
            //  'OS' => '',
            //  'size' => '',
            //  'ports' => '',
            //  'keyboard' => '',
            //  'audio' => '',
            //  'network_and_connection' => '',
            //  'security' => '',
            //  'quantity' => $quantity,
            //  'price' => '20990000',
            //  'status' => 'Còn hàng',
            //  'created_at' => now()],

            //  ['name' => 'Laptop gaming MSI Thin 15 B13UC 2044VN',
            //  'category_id' => 1,
            //  'manufactory_id' => 8,
            //  'CPU' => '',
            //  'VGA' => '',
            //  'RAM' => '',
            //  'hard_drive' => '',
            //  'display' => '',
            //  'battery' => '',
            //  'weight' => '',
            //  'material' => '',
            //  'OS' => '',
            //  'size' => '',
            //  'ports' => '',
            //  'keyboard' => '',
            //  'audio' => '',
            //  'network_and_connection' => '',
            //  'security' => '',
            //  'quantity' => $quantity,
            //  'price' => '20990000',
            //  'status' => 'Còn hàng',
            //  'created_at' => now()],

            //  ['name' => 'Laptop gaming MSI Thin 15 B13UC 2044VN',
            //  'category_id' => 1,
            //  'manufactory_id' => 8,
            //  'CPU' => '',
            //  'VGA' => '',
            //  'RAM' => '',
            //  'hard_drive' => '',
            //  'display' => '',
            //  'battery' => '',
            //  'weight' => '',
            //  'material' => '',
            //  'OS' => '',
            //  'size' => '',
            //  'ports' => '',
            //  'keyboard' => '',
            //  'audio' => '',
            //  'network_and_connection' => '',
            //  'security' => '',
            //  'quantity' => $quantity,
            //  'price' => '20990000',
            //  'status' => 'Còn hàng',
            //  'created_at' => now()],

            //  ['name' => 'Laptop gaming MSI Thin 15 B13UC 2044VN',
            //  'category_id' => 1,
            //  'manufactory_id' => 8,
            //  'CPU' => '',
            //  'VGA' => '',
            //  'RAM' => '',
            //  'hard_drive' => '',
            //  'display' => '',
            //  'battery' => '',
            //  'weight' => '',
            //  'material' => '',
            //  'OS' => '',
            //  'size' => '',
            //  'ports' => '',
            //  'keyboard' => '',
            //  'audio' => '',
            //  'network_and_connection' => '',
            //  'security' => '',
            //  'quantity' => $quantity,
            //  'price' => '20990000',
            //  'status' => 'Còn hàng',
            //  'created_at' => now()],
    }
}
